
- name: set facts
  set_fact:
    postgresql_shared_buffers: 2000MB

- name: install packages
  apt: 
    pkg: '{{ item }}'
  with_items:
    - python-psycopg2 # required for ansible postgresql_user
    - postgresql-9.5-postgis-2.2

- name: template postgresql.conf
  template: 
    src: postgresql.conf.j2
    dest: /etc/postgresql/9.5/main/postgresql.conf
    mode: 0644

- name: restart postgresql
  service: 
    name: postgresql
    state: restarted
