
- name: create dhis2 database user
  become: yes
  become_user: postgres
  postgresql_user:
    name: dhis2
    password: dhis2

- name: create dhis2 database
  become: yes
  become_user: postgres
  postgresql_db:
    owner: dhis2
    name: dhis2

- name: create demo home
  file: 
    path: '{{ dhis2_home }}'
    owner: tomcat8
    group: tomcat8
    state: directory

- name: template dhis.conf file
  copy: 
    src: dhis.conf
    dest: '{{ dhis2_home }}/dhis.conf'
    owner: tomcat8
    group: tomcat8
    mode: 0600

- name: clean tomcat root
  file:
    path: /var/lib/tomcat8/webapps/ROOT
    state: absent

- name: synchronize war to webapps
  synchronize:
    src: dhis2.war
    dest: /var/lib/tomcat8/webapps/ROOT.war

- name: restart tomcat
  service: 
    name: tomcat8
    state: restarted